apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marionette

resources:
  - namespace.yaml
  # Server
  - server/serviceaccount.yaml
  - server/configmap.yaml
  - server/pvc.yaml
  - server/deployment.yaml
  - server/service.yaml
  # Agent
  - agent/serviceaccount.yaml
  - agent/deployment.yaml
  # PostgreSQL
  - postgres/statefulset.yaml
  - postgres/service.yaml
  # Network policies
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: marionette/server
    newTag: latest
  - name: marionette/agent
    newTag: latest
