{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marionette.fullname" . }}-agent
  labels:
    {{- include "marionette.agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.agent.autoscaling.enabled }}
  replicas: {{ .Values.agent.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "marionette.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "marionette.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "marionette.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: {{ include "marionette.agent.image" . }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
            - name: MARIONETTE_SERVER
              value: "{{ include "marionette.fullname" . }}-server:{{ .Values.server.service.ports.grpc }}"
            - name: MARIONETTE_RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "marionette.fullname" . }}-secrets
                  key: runner-token
            - name: MARIONETTE_SANDBOX_MODE
              value: {{ .Values.agent.config.sandboxMode | quote }}
            - name: MARIONETTE_POOL_NAME
              value: {{ .Values.agent.config.poolName | quote }}
          volumeMounts:
            - name: workspace
              mountPath: /workspace
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: workspace
          emptyDir: {}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
