{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marionette.fullname" . }}-secrets
  labels:
    {{- include "marionette.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "marionette.databaseUrl" . | quote }}
  {{- else }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  master-key: {{ .Values.secrets.masterKey | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
  {{- if .Values.secrets.uiUsername }}
  ui-username: {{ .Values.secrets.uiUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.uiPassword }}
  ui-password: {{ .Values.secrets.uiPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.runnerToken }}
  runner-token: {{ .Values.secrets.runnerToken | quote }}
  {{- end }}
{{- end }}
