apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marionette-storage
  labels:
    app.kubernetes.io/name: marionette
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marionette-workspaces
  labels:
    app.kubernetes.io/name: marionette
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
