apiVersion: v1
kind: Service
metadata:
  name: marionette-server
  labels:
    app.kubernetes.io/name: marionette
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: marionette
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: admin
      port: 8081
      targetPort: admin
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
