#!/usr/bin/env bash
# smoke.sh — end-to-end acceptance walk for the Marionette restart (M1 gate).
#
# Owned by the coordinator. Lanes do not edit this file (see planning/00-mission.md).
# First full green: 2026-08-23 (manually driven; this script codifies that walk).
#
# Requirements: docker, a claude CLI login on the host (no ANTHROPIC_API_KEY needed),
# ports 8080/8081/9090/15432 free.
#
# KNOWN-GAPS (each step marked below; remove the workaround when fixed):
#   G3: mctl admin runner-tokens create prints empty fields       -> bootstrap via curl
set -u -o pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SMOKE_DIR="${SMOKE_DIR:-$ROOT/.claude/tmp/smoke}"
PG_PORT=15432
API=http://localhost:8080
ADMIN=http://localhost:8081
ADMIN_USER=admin
ADMIN_PASS="${SMOKE_ADMIN_PASS:-smokepass123}"
DB_URL="postgres://marionette:marionette@localhost:${PG_PORT}/marionette?sslmode=disable"
PASS=0; FAIL=0
mkdir -p "$SMOKE_DIR/workspace"

step() { # step <name> <cmd...>
  local name="$1"; shift
  if "$@" >"$SMOKE_DIR/step.log" 2>&1; then
    echo "PASS  $name"; PASS=$((PASS+1))
  else
    echo "FAIL  $name  (see $SMOKE_DIR/step.log)"; FAIL=$((FAIL+1))
    echo "---- last lines ----"; tail -8 "$SMOKE_DIR/step.log"
    cleanup; exit 1
  fi
}

cleanup() {
  [ -f "$SMOKE_DIR/agent.pid" ] && kill "$(cat "$SMOKE_DIR/agent.pid")" 2>/dev/null
  [ -f "$SMOKE_DIR/server.pid" ] && kill "$(cat "$SMOKE_DIR/server.pid")" 2>/dev/null
  docker rm -f marionette-smoke-pg >/dev/null 2>&1
  true
}
trap cleanup INT TERM

json() { python3 -c "import json,sys;d=json.load(sys.stdin);print(eval(\"d$1\"))" 2>/dev/null; }

echo "== marionette smoke =="

# 0. build
step "build" make -C "$ROOT" build

# 1. fresh database from migrations only
step "pg-fresh" bash -c "docker rm -f marionette-smoke-pg >/dev/null 2>&1; docker run -d --name marionette-smoke-pg -e POSTGRES_USER=marionette -e POSTGRES_PASSWORD=marionette -e POSTGRES_DB=marionette -p ${PG_PORT}:5432 postgres:16-alpine && sleep 5"
step "migrations" docker run --rm -v "$ROOT/migrations:/migrations" migrate/migrate:v4.18.1 -path=/migrations -database "postgres://marionette:marionette@host.docker.internal:${PG_PORT}/marionette?sslmode=disable" up

# 2. server up, admin fails closed
step "server-up" bash -c "cd '$ROOT' && MARIONETTE_DATABASE_URL='$DB_URL' MARIONETTE_MASTER_KEY=\$(openssl rand -hex 32) MARIONETTE_ENCRYPTION_KEY=\$(openssl rand -hex 32) MARIONETTE_UI_USERNAME=$ADMIN_USER MARIONETTE_UI_PASSWORD=$ADMIN_PASS nohup ./bin/server --config configs/local.yaml >| '$SMOKE_DIR/server.log' 2>&1 & echo \$! >| '$SMOKE_DIR/server.pid'; sleep 4"
step "api-health" bash -c "[ \"\$(curl -s -o /dev/null -w '%{http_code}' $API/health)\" = 200 ]"
step "admin-fails-closed" bash -c "[ \"\$(curl -s -o /dev/null -w '%{http_code}' $ADMIN/admin/api/v1/keys)\" = 401 ]"

# 3. bootstrap credentials (G3: curl, not mctl)
step "api-key" bash -c "curl -s -u $ADMIN_USER:$ADMIN_PASS -X POST $ADMIN/admin/api/v1/keys -H 'Content-Type: application/json' -d '{\"name\":\"smoke\",\"scopes\":[\"*\"]}' | python3 -c 'import json,sys;print(json.load(sys.stdin)[\"raw_token\"])' >| '$SMOKE_DIR/api.key'"
step "runner-token" bash -c "curl -s -u $ADMIN_USER:$ADMIN_PASS -X POST $ADMIN/admin/api/v1/runner-tokens -H 'Content-Type: application/json' -d '{\"pool_name\":\"default\"}' | python3 -c 'import json,sys;print(json.load(sys.stdin)[\"raw_token\"])' >| '$SMOKE_DIR/runner.token'"
APIKEY=$(cat "$SMOKE_DIR/api.key")

# 4. pool runner joins
step "agent-up" bash -c "cd '$ROOT' && MARIONETTE_RUNNER_TOKEN=\$(cat '$SMOKE_DIR/runner.token') nohup ./bin/agent --server localhost:9090 --pool default --name smoke-runner --sandbox-mode none --workspace '$SMOKE_DIR/workspace' --log-format console >| '$SMOKE_DIR/agent.log' 2>&1 & echo \$! >| '$SMOKE_DIR/agent.pid'; sleep 4"
step "runner-registered" bash -c "curl -s -H 'Authorization: Bearer $APIKEY' $API/api/v1/runners | grep -q '\"smoke-runner\"'"
RUNNER_ID=$(curl -s -H "Authorization: Bearer $APIKEY" $API/api/v1/runners | python3 -c "import json,sys;print(json.load(sys.stdin)['items'][0]['id'])")

# 5. session + task (host claude login, BYOK not needed)
step "session-create" bash -c "cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY sessions create --agent claude --name smoke -o json | python3 -c 'import json,sys;print(json.load(sys.stdin)[\"id\"])' >| '$SMOKE_DIR/session.id'"
SESS=$(cat "$SMOKE_DIR/session.id")
step "task-create" bash -c "cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY tasks create --session $SESS --prompt 'Run this exact bash command and then stop: echo marionette-m1-alive' -o json | python3 -c 'import json,sys;print(json.load(sys.stdin)[\"id\"])' >| '$SMOKE_DIR/task.id'"
TASK=$(cat "$SMOKE_DIR/task.id")

# 6. permission gate: wait for the pending request, approve it
step "permission-pending" bash -c "for i in \$(seq 1 30); do P=\$(curl -s -H 'Authorization: Bearer $APIKEY' '$API/api/v1/permissions?status=pending' | python3 -c 'import json,sys;i=json.load(sys.stdin).get(\"items\",[]);print(i[0][\"id\"] if i else \"\")'); [ -n \"\$P\" ] && echo \$P >| '$SMOKE_DIR/perm.id' && exit 0; sleep 2; done; exit 1"
step "permission-approve" bash -c "curl -s -X POST -H 'Authorization: Bearer $APIKEY' -H 'Content-Type: application/json' -d '{\"reason\":\"smoke\"}' $API/api/v1/permissions/\$(cat '$SMOKE_DIR/perm.id')/approve -o /dev/null -w '%{http_code}' | grep -qE '200|204'"

# 7. completion, tokens, logs
step "task-completed" bash -c "for i in \$(seq 1 45); do S=\$(cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY tasks get $TASK -o json | python3 -c 'import json,sys;print(json.load(sys.stdin)[\"status\"])'); [ \"\$S\" = completed ] && exit 0; [ \"\$S\" = failed ] && exit 1; sleep 2; done; exit 1"
step "tokens-reported" bash -c "curl -s -H 'Authorization: Bearer $APIKEY' $API/api/v1/tasks/$TASK | python3 -c 'import json,sys;d=json.load(sys.stdin);sys.exit(0)'"
step "logs-contain-output" bash -c "curl -s -H 'Authorization: Bearer $APIKEY' $API/api/v1/tasks/$TASK/logs | grep -q marionette-m1-alive"

# 8. lifecycle: suspend, resume, terminate
step "suspend" bash -c "cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY sessions suspend $SESS && sleep 3 && ./bin/mctl --server $API --api-key $APIKEY sessions get $SESS -o json | grep -q '\"suspended\"'"
step "resume" bash -c "cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY sessions resume $SESS && sleep 5 && ./bin/mctl --server $API --api-key $APIKEY sessions get $SESS -o json | grep -q '\"active\"'"
step "terminate" bash -c "cd '$ROOT' && ./bin/mctl --server $API --api-key $APIKEY sessions terminate $SESS && sleep 3 && ./bin/mctl --server $API --api-key $APIKEY sessions get $SESS -o json | grep -q '\"terminated\"'"

cleanup
echo "== $PASS passed, $FAIL failed =="
