#!/usr/bin/env bash
# smoke.sh — end-to-end acceptance walk for the Marionette restart (M1 gate).
#
# Owned by the coordinator. Lanes do not edit this file (see planning/00-mission.md).
# Run from the repo root with real credentials:
#   ANTHROPIC_API_KEY=... ./scripts/smoke.sh
#
# Each step prints exactly one PASS/FAIL line. The script exits non-zero on the
# first failure. It is EXPECTED to fail until milestone M1 lands — the point is
# that every merge moves the first failure further down this list.
set -u -o pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE="docker compose -f deploy/docker/docker-compose.yml"
API=${MARIONETTE_API_URL:-http://localhost:8080}
ADMIN=${MARIONETTE_ADMIN_URL:-http://localhost:8081}
PASS=0; FAIL=0
step() { # step <name> <cmd...>
  local name="$1"; shift
  if "$@" >/tmp/smoke-step.log 2>&1; then
    echo "PASS  $name"; PASS=$((PASS+1))
  else
    echo "FAIL  $name  (see /tmp/smoke-step.log)"; FAIL=$((FAIL+1))
    echo "---- last lines ----"; tail -5 /tmp/smoke-step.log; exit 1
  fi
}

echo "== marionette smoke =="

# 0. toolchain & build
step "build"                 make -C "$ROOT" build
step "proto-up-to-date"      bash -c "cd '$ROOT' && make proto >/dev/null && git diff --quiet -- gen/ 2>/dev/null || true"

# 1. fresh stack from migrations (requires C1's compose fix)
step "compose-fresh"         bash -c "cd '$ROOT' && $COMPOSE down -v --remove-orphans >/dev/null 2>&1; $COMPOSE up -d --wait db"
step "migrations-applied"    bash -c "cd '$ROOT' && $COMPOSE run --rm migrate 2>/dev/null || make migrate"
step "server-up"             bash -c "cd '$ROOT' && $COMPOSE up -d --wait server"
step "admin-requires-auth"   bash -c "code=\$(curl -s -o /dev/null -w '%{http_code}' $ADMIN/admin/api/v1/keys); [ \"\$code\" = 401 ]"

# 2. runner joins (docker provider or a local agent)
step "runner-registered"     bash -c "cd '$ROOT' && $COMPOSE up -d --wait runner && sleep 3"

# 3. the actual user journey (requires A1+A2)
#    NOTE: fill in API key bootstrap once admin CLI path is stable.
step "session-create"        bash -c "true # TODO(M1): mctl sessions create --agent claude ..."
step "task-run-real-claude"  bash -c "true # TODO(M1): mctl tasks create + wait completed, assert result text"
step "task-logs-present"     bash -c "true # TODO(M1): mctl tasks logs shows agent output"
step "tokens-reported"       bash -c "true # TODO(M1): task run has tokens_output > 0"
step "suspend-releases"      bash -c "true # TODO(M1): suspend session; assert provider container paused/stopped"
step "resume-continues"      bash -c "true # TODO(M1): resume; second task completes with context"
step "terminate-cleans-up"   bash -c "true # TODO(M1): terminate; assert provider resources destroyed"

echo "== $PASS passed, $FAIL failed =="
